#!/bin/sh 

set -e

ln -sf "$PWD/.zshrc" ~/
ln -sf "$PWD/.vimrc" ~/
ln -sf "$PWD/.bashrc" ~/
# need to setup a PATH directive for scripts (done inside .zshrc)
ln -sf "$PWD/scripts" ~/.local/bin/scripts
ln -sf "$PWD/i3" ~/.config
ln -sf "$PWD/i3status-rust" ~/.config
# may need to mkdir -p ~/.screenlayout first
ln -sf "$PWD/default-i3.sh" ~/.screenlayout/


