#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  PORT="$1:$1"
  printf "Port selected: '%s'\n" "${PORT}"
else
  PORT="9090:9090"
  echo "Port default of '9090:9090' selected"
fi

docker run -it --rm \
    -w "/go/src/github.com/cosmtrek/hub" \
    -v $(pwd):/go/src/github.com/cosmtrek/hub \
    -p "$PORT" \
    cosmtrek/air



