#!/bin/bash
printf "exporting faasd creds to env\n"
echo "usage: . faas-creds"

export OPENFAAS_PREFIX=docker.io/danielmichaels
export TLD=dansult.space
export DOMAIN=openfaas.k3s.$TLD
export OPENFAAS_URL=https://$DOMAIN

PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)

echo $PASSWORD | faas-cli login -s
