#!/usr/bin/env bash

#set -x

github=https://api.github.com
owner=danielmichaels
repo=zet

fetch-contents() {
j=$(curl -sS ${github}/repos/${owner}/${repo}/contents)
}

parse-html() {
html=$(echo $j | jq .[].html_url)
}

retrieve-readme-path() {
isosec=$(echo $j | jq .[].path)
}

retrieve-readme-title() {
for i in $isosec; do
  title=$(curl -sS ${github}/repos/${owner}/${repo}/readme/${i} | jq -r '.content' | base64 -d | head -n 1 | sed 's/# //' | tr '\n' ' ')
  sleep 1
  echo ${title}
  printf "%s: %s" $i ${title}
done
}

fetch-contents
parse-html
retrieve-readme-path
#retrieve-readme-title
echo $j | jq .
