#!/usr/bin/env bash

if ! command -v nix > /dev/null 2&>1; then
    echo "attempting to install nix locally. it may prompt you for sudo"
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
fi
mkdir -p ~/.config/nix
if [[ ! -f "$HOME/.config/nix/nix.conf" ]]; then
    echo "Adding nix experimental features flake"
    echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
fi

$HOME/.nix-profile/bin/nix profile install github:ublue-os/fleek/main

curl https://github.com/ublue-os/fleek/releases/latest/download/fleek_Linux_x86_64.tar.gz -LsS -o /tmp/fleek.tar.gz

tar -xvf /tmp/fleek.tar.gz -C /tmp fleek
mv /tmp/fleek "${HOME}/.local/bin"

