#!/usr/bin/env bash

PROGNAME="hostmount"
    usage="${PROGNAME} <container> -- Host mount local files into k3s

    Must be located in the root directory of the git repo"

  test ! -n "${1}" && echo "$usage" && exit 1

  service="${1:-}"
  jsonfile=/tmp/patch.json

  json='
  {
    "spec": {
      "template": {
        "spec": {
          "containers": [
            "name": "%s",
            "command": [
              "sh",
              "-c",
              "apk add py-watchdog && watchmedo auto-restart -d $PWD -R --
entrypoint.py"
              ],
              "volumeMounts": [
                "mountPath": "/usr/src/app",
                "name": "host-mount"
                }
              ]
            }
          ],
          "volumes": [
            {
              "name": "host-mount",
              "hostPath": {
                "path": "%s"
                }
              }
            ]
          }
        }
      }
    }
  }
  '

  printf "$json" "$service" "$(pwd)" > $jsonfile
  cat $jsonfile

  kubectl patch deployment "${service}" -n "${namespace:-default}" --
patch-file $jsonfile
