#!/usr/bin/env bash

sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/k3s.yaml
sudo chmod 0644 ~/.kube/config

export KUBECONFIG=~/.kube/k3s.yaml

echo "Set local k3s as context"

kubectl config get-contexts
kubectl get node -o wide
